//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.20 at 05:28:26 ÏÂÎç CST 
//


package com.sohu.suc.JAXB;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for message_template complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="message_template">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="top_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parent_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="matcher_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="converter">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".+\..+:{1}.+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://i.sohu.com/message/message_template_info}patterns"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message_template", propOrder = {
    "type",
    "topType",
    "parentType",
    "parent",
    "matcherClass",
    "converter",
    "patternList"
})
public class MessageTemplate {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(name = "top_type", required = true)
    protected String topType;
    @XmlElement(name = "parent_type", required = true)
    protected String parentType;
    @XmlElement(required = true)
    protected String parent;
    @XmlElement(name = "matcher_class", required = true)
    protected String matcherClass;
    @XmlElement(required = true)
    protected String converter;
    @XmlElementWrapper(name="patterns")
    @XmlElement(name="pattern", required = true)
    protected List<Pattern> patternList;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the topType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopType() {
        return topType;
    }

    /**
     * Sets the value of the topType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopType(String value) {
        this.topType = value;
    }

    /**
     * Gets the value of the parentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentType(String value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the matcherClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatcherClass() {
        return matcherClass;
    }

    /**
     * Sets the value of the matcherClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatcherClass(String value) {
        this.matcherClass = value;
    }

    /**
     * Gets the value of the converter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConverter() {
        return converter;
    }

    /**
     * Sets the value of the converter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConverter(String value) {
        this.converter = value;
    }

    /**
     * Gets the value of the patterns property.
     * 
     * @return
     *     possible object is
     *     {@link Patterns }
     *     
     */
    public List<Pattern> getPatternList() {
		return patternList;
	}

	public void setPatternList(List<Pattern> patternList) {
		this.patternList = patternList;
	}

}
